# Generated by Django 3.2.7 on 2021-09-30 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'department',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('contactnum', models.IntegerField()),
                ('email', models.EmailField(max_length=30)),
                ('employeeid', models.CharField(max_length=5, verbose_name='Employee Id Number')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emp.department', verbose_name='department')),
            ],
            options={
                'verbose_name': 'Employee',
            },
        ),
    ]
